name: test CI/CD

on:
  push:
    branches: ["main"]
  pull:
    branches: ["main"]
jobs:
  develop_build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取最新提交的代码
        uses: actions/checkout@v3

      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: 项目打包
        run: mvn -B package

      - name: 上传jar包和启动脚本到服务器中
        run: sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./target/test.jar ./deploy.sh root@${{secrets.REMOTE_IP}}:/home/test/

      - name: 启动项目
        run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "cd /home/test/ && chmod +x deploy.sh && sh ./deploy.sh start"
